Repository CS2103-AY1819S1-T16-3/main, pull requests merged in 2018-11, with the labels that each got.

#102 Map now renders placeholders for orders
  src/main/java/seedu/address/ui/Dashboard.java
  src/main/java/seedu/address/ui/Display.java
  src/main/java/seedu/address/ui/MapPanel.java
  src/main/java/seedu/address/ui/util/MapDataUtil.java
  src/main/resources/images/order_placeholder.png
  src/main/resources/images/placeholder.png
  src/main/resources/images/receipt.png
  src/main/resources/images/red_placeholder.png
  src/main/resources/images/shipping.png
  src/main/resources/view/Display.fxml
  src/main/resources/view/TestTheme.css
Labels: priority.High, v1.3

#125 Fix bug in progress bar
  src/main/java/seedu/address/ui/Display.java
Labels: v1.3

#128 Flesh out UI and update seed data
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/ui/MapPanel.java
  src/main/resources/images/placeholder.png
  src/main/resources/view/Display.fxml
  src/main/resources/view/TestTheme.css
Labels: v1.3

#129 Basic TouchUp for order select
  src/main/java/seedu/address/ui/display/OrderDisplayCard.java
  src/main/resources/view/display/OrderDisplayCard.fxml
Labels: v1.3

#130 Update User Guide
  docs/UserGuide.adoc
  docs/images/Ui.png
Labels: v1.3

#122 DeveloperGuide.adoc: Update Model UML diagram
  docs/DeveloperGuide.adoc
  docs/diagrams/ModelComponentClassDiagram.pptx
  docs/images/ModelClassDiagram.png
Labels: type.Task

#152 Add deliveryman select
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/commands/deliveryman/DeliverymanSelectCommand.java
  src/main/java/seedu/address/logic/parser/deliveryman/DeliverymanCommandParser.java
  src/main/java/seedu/address/logic/parser/deliveryman/DeliverymanSelectCommandParser.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/deliveryman/DeliverymanSelectCommandTest.java
  src/test/java/seedu/address/logic/parser/deliveryman/DeliverymanSelectCommandParserTest.java
Labels: v1.4

#163 Update UserGuide
  docs/UserGuide.adoc
Labels: v1.4

#157 Remove undo & redo commands
  src/main/java/seedu/address/logic/commands/RedoCommand.java
  src/main/java/seedu/address/logic/commands/UndoCommand.java
  src/main/java/seedu/address/logic/parser/OrderBookParser.java
  src/test/java/seedu/address/logic/commands/RedoCommandTest.java
  src/test/java/seedu/address/logic/commands/UndoCommandTest.java
  src/test/java/seedu/address/logic/commands/order/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/order/EditCommandTest.java
  src/test/java/seedu/address/logic/parser/OrderBookParserTest.java
  src/test/java/systemtests/AddCommandSystemTest.java
  src/test/java/systemtests/ClearCommandSystemTest.java
  src/test/java/systemtests/DeleteCommandSystemTest.java
  src/test/java/systemtests/EditCommandSystemTest.java
  src/test/java/systemtests/FindCommandSystemTest.java
  src/test/java/systemtests/SelectCommandSystemTest.java
Labels: type.Bug

#131 /order done
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/commands/order/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/order/DoneCommand.java
  src/main/java/seedu/address/logic/commands/order/EditCommand.java
  src/main/java/seedu/address/logic/parser/order/DoneCommandParser.java
  src/main/java/seedu/address/logic/parser/order/OrderCommandParser.java
  src/main/java/seedu/address/model/deliveryman/Deliveryman.java
  src/main/java/seedu/address/model/order/Order.java
  src/main/java/seedu/address/model/order/OrderStatus.java
  src/test/java/seedu/address/logic/commands/order/DoneCommandTest.java
  src/test/java/seedu/address/logic/parser/order/DoneCommandParserTest.java
  src/test/java/seedu/address/testutil/DeliverymanBuilder.java
  src/test/java/seedu/address/testutil/OrderBuilder.java
Labels: v1.4

#161 Fix signup bug
  src/main/java/seedu/address/logic/commands/LoginCommand.java
  src/main/java/seedu/address/model/user/User.java
Labels: type.Bug, v1.4

#168 Update DG for Storage Component
  docs/DeveloperGuide.adoc
  docs/diagrams/StorageComponentClassDiagram.pptx
  docs/diagrams/StorageSequenceDiagram.pptx
  docs/images/StorageClassDiagram.png
  docs/images/StorageSequenceDiagram.png
Labels: good first issue

#164 DeveloperGuide.adoc: Update Logic component
  docs/DeveloperGuide.adoc
  docs/diagrams/HighLevelSequenceDiagrams.pptx
  docs/diagrams/LogicComponentClassDiagram.pptx
  docs/diagrams/LogicComponentSequenceDiagram.pptx
  docs/images/DeleteOrderSdForLogic.png
  docs/images/LogicClassDiagram.png
  docs/images/SDforDeleteOrder.png
  docs/images/SDforDeleteOrderEventHandling.png
Labels: v1.4

#155 Find Order By Status
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/order/FindCommandParser.java
  src/main/java/seedu/address/logic/parser/order/OrderPredicateUtil.java
  src/main/java/seedu/address/logic/parser/order/OrderStatusPredicateUtil.java
  src/main/java/seedu/address/model/order/OrderStatus.java
  src/main/java/seedu/address/model/order/OrderStatusContainsKeywordPredicate.java
  src/test/data/XmlFoodZoomTest/typicalFoodZoom.xml
  src/test/data/XmlSerializableOrderBookTest/typicalOrdersOrderBook.xml
  src/test/java/seedu/address/logic/parser/order/FindCommandParserTest.java
  src/test/java/seedu/address/logic/parser/order/OrderPredicateUtilTest.java
  src/test/java/seedu/address/logic/parser/order/OrderStatusPredicateUtilTest.java
  src/test/java/seedu/address/model/order/OrderStatusContainsKeywordPredicateTest.java
  src/test/java/seedu/address/testutil/TypicalOrders.java
  src/test/java/systemtests/FindCommandSystemTest.java
Labels: v1.4

#177 Add login,signup,order done to appendix H
  docs/DeveloperGuide.adoc
Labels: v1.4

#171 Modifications to UI Elements
  src/main/java/seedu/address/ui/Display.java
  src/main/java/seedu/address/ui/OrderCard.java
  src/main/java/seedu/address/ui/display/OrderDisplayCard.java
  src/main/resources/images/cutlery.png
  src/main/resources/view/OrderListCard.fxml
  src/main/resources/view/TestTheme.css
  src/main/resources/view/display/OrderDisplayCard.fxml
  src/test/java/guitests/guihandles/OrderCardHandle.java
Labels: v1.4

#180 Appendix H: Find and Edit for Order
  docs/DeveloperGuide.adoc
Labels: v1.4

#193 PPP kohchihao.adoc: Add order done
  docs/UserGuide.adoc
  docs/team/kohchihao.adoc
Labels: priority.High

#196 Fix find command bugs for order and deliveryman
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/team/jinyingtan.adoc
  src/main/java/seedu/address/logic/parser/deliveryman/DeliverymanFindCommandParser.java
  src/main/java/seedu/address/logic/parser/order/OrderPredicateUtil.java
  src/main/java/seedu/address/model/deliveryman/DeliverymanNameContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/order/OrderFoodContainsKeywordPredicate.java
  src/main/java/seedu/address/model/order/OrderNameContainsKeywordPredicate.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/deliveryman/DeliverymanFindCommandTest.java
  src/test/java/seedu/address/logic/commands/order/FindCommandTest.java
  src/test/java/seedu/address/logic/parser/deliveryman/DeliverymanCommandParserTest.java
  src/test/java/seedu/address/logic/parser/deliveryman/DeliverymanFindCommandParserTest.java
  src/test/java/seedu/address/logic/parser/order/FindCommandParserTest.java
  src/test/java/seedu/address/logic/parser/order/OrderCommandParserTest.java
  src/test/java/seedu/address/logic/parser/order/OrderPredicateUtilTest.java
  src/test/java/seedu/address/model/deliveryman/DeliverymanNameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/order/OrderFoodContainsKeywordPredicateTest.java
  src/test/java/seedu/address/model/order/OrderNameContainsKeywordPredicateTest.java
  src/test/java/systemtests/FindCommandSystemTest.java
Labels: bug

#197 Add assign limit
  docs/UserGuide.adoc
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/AssignCommand.java
  src/main/java/seedu/address/model/deliveryman/Deliveryman.java
  src/main/java/seedu/address/model/deliveryman/exceptions/OrdersLimitExceededException.java
  src/main/java/seedu/address/model/order/Order.java
  src/test/java/seedu/address/logic/commands/AssignCommandTest.java
Labels: enhancement, good first issue, v1.4
