Repository CS2103-AY1819S1-T16-3/main, pull requests merged in 2018-10, with the labels that each got.

#15 Add deliveryman
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/commons/events/model/DeliverymenListChangedEvent.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/model/deliveryman/Deliveryman.java
  src/main/java/seedu/address/model/deliveryman/DeliverymenList.java
  src/main/java/seedu/address/model/deliveryman/UniqueDeliverymenList.java
  src/main/java/seedu/address/model/deliveryman/VersionedDeliverymenList.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/Storage.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/main/java/seedu/address/storage/XmlFileStorage.java
  src/main/java/seedu/address/storage/deliveryman/DeliverymenListStorage.java
  src/main/java/seedu/address/storage/deliveryman/XmlAdaptedDeliveryman.java
  src/main/java/seedu/address/storage/deliveryman/XmlDeliverymenListStorage.java
  src/main/java/seedu/address/storage/deliveryman/XmlSerializableDeliverymenList.java
  src/test/data/XmlDeliverymenListStorageTest/NotXmlFormatDeliverymenList.xml
  src/test/data/XmlDeliverymenListStorageTest/invalidAndValidDeliverymenDeliverymenList.xml
  src/test/data/XmlDeliverymenListStorageTest/invalidDeliverymanDeliverymenList.xml
  src/test/data/XmlSerializableDeliverymenListTest/duplicateDeliverymenDeliverymenList.xml
  src/test/data/XmlSerializableDeliverymenListTest/invalidDeliverymanDeliverymenList.xml
  src/test/data/XmlSerializableDeliverymenListTest/typicalDeliverymenDeliverymenList.xml
  src/test/data/XmlUtilTest/invalidDeliverymanField.xml
  src/test/data/XmlUtilTest/validDeliveryman.xml
  src/test/data/XmlUtilTest/validDeliverymenList.xml
  src/test/java/seedu/address/TestApp.java
  src/test/java/seedu/address/commons/util/XmlUtilTest.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/logic/commands/LoginCommandTest.java
  src/test/java/seedu/address/logic/commands/RedoCommandTest.java
  src/test/java/seedu/address/logic/commands/SelectCommandTest.java
  src/test/java/seedu/address/logic/commands/SignUpCommandTest.java
  src/test/java/seedu/address/logic/commands/UndoCommandTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/deliveryman/DeliverymanTest.java
  src/test/java/seedu/address/model/deliveryman/DeliverymenListTest.java
  src/test/java/seedu/address/model/deliveryman/UniqueDeliverymenListTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
  src/test/java/seedu/address/storage/deliveryman/XmlAdaptedDeliverymanTest.java
  src/test/java/seedu/address/storage/deliveryman/XmlDeliverymenListStorageTest.java
  src/test/java/seedu/address/storage/deliveryman/XmlSerializableDeliverymenListTest.java
  src/test/java/seedu/address/testutil/DeliverymanBuilder.java
  src/test/java/seedu/address/testutil/DeliverymanUtil.java
  src/test/java/seedu/address/testutil/DeliverymenListBuilder.java
  src/test/java/seedu/address/testutil/TypicalDeliverymen.java
Labels: V1.1

#20 Adding Route
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/commons/events/model/RouteListChangedEvent.java
  src/main/java/seedu/address/logic/commands/CreateRouteCommand.java
  src/main/java/seedu/address/logic/commands/RouteCommand.java
  src/main/java/seedu/address/logic/parser/CreateRouteCommandParser.java
  src/main/java/seedu/address/logic/parser/OrderBookParser.java
  src/main/java/seedu/address/logic/parser/RouteCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/model/route/ReadOnlyRouteList.java
  src/main/java/seedu/address/model/route/Route.java
  src/main/java/seedu/address/model/route/RouteList.java
  src/main/java/seedu/address/model/route/UniqueRouteList.java
  src/main/java/seedu/address/model/route/VersionedRouteList.java
  src/main/java/seedu/address/model/route/exceptions/DuplicateRouteException.java
  src/main/java/seedu/address/model/route/exceptions/RouteNotFoundException.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/Storage.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/main/java/seedu/address/storage/XmlFileStorage.java
  src/main/java/seedu/address/storage/route/RouteListStorage.java
  src/main/java/seedu/address/storage/route/XmlAdaptedRoute.java
  src/main/java/seedu/address/storage/route/XmlRouteListStorage.java
  src/main/java/seedu/address/storage/route/XmlSerializableRouteList.java
  src/test/java/seedu/address/TestApp.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/LoginCommandTest.java
  src/test/java/seedu/address/logic/commands/RedoCommandTest.java
  src/test/java/seedu/address/logic/commands/SignUpCommandTest.java
  src/test/java/seedu/address/logic/commands/UndoCommandTest.java
  src/test/java/seedu/address/logic/commands/order/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/order/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/order/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/order/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/order/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/order/ListCommandTest.java
  src/test/java/seedu/address/logic/commands/order/SelectCommandTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/route/RouteListTest.java
  src/test/java/seedu/address/model/route/RouteTest.java
  src/test/java/seedu/address/model/route/UniqueRouteListTest.java
  src/test/java/seedu/address/model/route/VersionedRouteListTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
  src/test/java/seedu/address/testutil/RouteBuilder.java
  src/test/java/seedu/address/testutil/RouteListBuilder.java
  src/test/java/seedu/address/testutil/TypicalRoutes.java
Labels: V1.1

#61 Add OrderFindCommand Implementation Documentation
  docs/DeveloperGuide.adoc
  docs/diagrams/OrderFindCommandSequenceDiagram.pptx
  docs/images/OrderFindSequenceDiagram.png
Labels: priority.Medium, v1.2

#55 Order Edit command
  src/main/java/seedu/address/logic/commands/order/EditCommand.java
  src/main/java/seedu/address/logic/parser/order/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/order/OrderCommandParser.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/order/EditCommandTest.java
  src/test/java/seedu/address/logic/parser/order/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/order/EditOrderDescriptorTest.java
  src/test/java/seedu/address/logic/parser/order/OrderCommandParserTest.java
  src/test/java/seedu/address/testutil/EditOrderDescriptorBuilder.java
  src/test/java/seedu/address/testutil/OrderUtil.java
  src/test/java/systemtests/EditCommandSystemTest.java
  src/test/java/systemtests/OrderBookSystemTest.java
Labels: priority.Medium, v1.2

#72 V1.2 loginsignup
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/commons/events/model/UserLoggedInEvent.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/LoginCommand.java
  src/main/java/seedu/address/logic/commands/SignUpCommand.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/LoginCommandTest.java
  src/test/java/seedu/address/logic/commands/SignUpCommandTest.java
  src/test/java/systemtests/AddCommandSystemTest.java
  src/test/java/systemtests/ClearCommandSystemTest.java
  src/test/java/systemtests/DeleteCommandSystemTest.java
  src/test/java/systemtests/EditCommandSystemTest.java
  src/test/java/systemtests/FindCommandSystemTest.java
  src/test/java/systemtests/HelpCommandSystemTest.java
  src/test/java/systemtests/LoginCommandSystemTest.java
  src/test/java/systemtests/SelectCommandSystemTest.java
  src/test/java/systemtests/SignUpCommandSystemTest.java
Labels: priority.High, v1.2

#50 Refactor Route: create a route containing multiple orders
  src/main/java/seedu/address/commons/core/index/Index.java
  src/main/java/seedu/address/logic/commands/route/CreateRouteCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/route/CreateRouteCommandParser.java
  src/main/java/seedu/address/model/route/Route.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/route/XmlAdaptedRoute.java
  src/test/data/XmlRouteListStorageTest/invalidAndValidRouteRouteList.xml
  src/test/data/XmlRouteListStorageTest/invalidRouteRouteList.xml
  src/test/data/XmlSerializableRouteListTest/duplicateRouteRouteList.xml
  src/test/data/XmlSerializableRouteListTest/typicalRouteRouteList.xml
  src/test/java/seedu/address/logic/commands/route/CreateRouteCommandTest.java
  src/test/java/seedu/address/logic/parser/route/CreateRouteCommandParserTest.java
  src/test/java/seedu/address/logic/parser/route/RouteCommandParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/route/RouteListTest.java
  src/test/java/seedu/address/model/route/RouteTest.java
  src/test/java/seedu/address/model/route/UniqueRouteListTest.java
  src/test/java/seedu/address/model/route/VersionedRouteListTest.java
  src/test/java/seedu/address/storage/route/XmlAdaptedRouteTest.java
  src/test/java/seedu/address/storage/route/XmlRouteListStorageTest.java
  src/test/java/seedu/address/testutil/TypicalRoutes.java
  src/test/java/seedu/address/testutil/route/RouteBuilder.java
  src/test/java/seedu/address/testutil/route/RouteUtil.java
Labels: priority.High, severity.Medium, status.Ongoing, v1.2

#64 Add documentation for Route creation in Developer Guide
  docs/DeveloperGuide.adoc
  docs/images/CreateRouteCommandSequenceDiagram1.png
  docs/images/CreateRouteCommandSequenceDiagram2.png
Labels: priority.Medium, v1.2

#73 UI Screen
  src/main/java/seedu/address/commons/events/ui/DeliveryManPanelSelectionChangedEvent.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/ui/DeliverymanCard.java
  src/main/java/seedu/address/ui/DeliverymanListPanel.java
  src/main/java/seedu/address/ui/Display.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/OrderCard.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/images/cutlery.png
  src/main/resources/images/deliveryboy.png
  src/main/resources/images/scooter.png
  src/main/resources/images/sgmap.png
  src/main/resources/view/CommandBox.fxml
  src/main/resources/view/DeliverymanListCard.fxml
  src/main/resources/view/DeliverymanListPanel.fxml
  src/main/resources/view/Display.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/MapCard.fxml
  src/main/resources/view/OrderListCard.fxml
  src/main/resources/view/TestTheme.css
  src/test/java/guitests/guihandles/DisplayPanelHandle.java
  src/test/java/guitests/guihandles/MainWindowHandle.java
  src/test/java/guitests/guihandles/OrderCardHandle.java
  src/test/java/seedu/address/ui/OrderCardTest.java
  src/test/java/seedu/address/ui/OrderListPanelTest.java
  src/test/java/seedu/address/ui/testutil/GuiTestAssert.java
  src/test/java/systemtests/DeleteCommandSystemTest.java
  src/test/java/systemtests/EditCommandSystemTest.java
  src/test/java/systemtests/FindCommandSystemTest.java
  src/test/java/systemtests/HelpCommandSystemTest.java
  src/test/java/systemtests/OrderBookSystemTest.java
  src/test/java/systemtests/SelectCommandSystemTest.java
Labels: priority.Medium, v1.2

#59 Add model ids
  src/main/java/seedu/address/logic/commands/deliveryman/DeliverymanAddCommand.java
  src/main/java/seedu/address/logic/commands/order/AddCommand.java
  src/main/java/seedu/address/model/IdObject.java
  src/main/java/seedu/address/model/OrderBook.java
  src/main/java/seedu/address/model/deliveryman/Deliveryman.java
  src/main/java/seedu/address/model/deliveryman/DeliverymenList.java
  src/main/java/seedu/address/model/order/Order.java
  src/main/java/seedu/address/model/route/Route.java
  src/main/java/seedu/address/model/route/RouteList.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/XmlAdaptedOrder.java
  src/main/java/seedu/address/storage/deliveryman/XmlAdaptedDeliveryman.java
  src/main/java/seedu/address/storage/route/XmlAdaptedRoute.java
  src/test/data/XmlDeliverymenListStorageTest/invalidAndValidDeliverymenDeliverymenList.xml
  src/test/data/XmlRouteListStorageTest/invalidAndValidRouteRouteList.xml
  src/test/data/XmlRouteListStorageTest/invalidRouteRouteList.xml
  src/test/data/XmlSerializableDeliverymenListTest/duplicateDeliverymenDeliverymenList.xml
  src/test/data/XmlSerializableDeliverymenListTest/invalidDeliverymanDeliverymenList.xml
  src/test/data/XmlSerializableDeliverymenListTest/typicalDeliverymenDeliverymenList.xml
  src/test/data/XmlSerializableOrderBookTest/duplicateOrderOrderBook.xml
  src/test/data/XmlSerializableOrderBookTest/invalidOrderOrderBook.xml
  src/test/data/XmlSerializableOrderBookTest/typicalOrdersOrderBook.xml
  src/test/data/XmlSerializableRouteListTest/duplicateRouteRouteList.xml
  src/test/data/XmlSerializableRouteListTest/invalidRouteRouteList.xml
  src/test/data/XmlSerializableRouteListTest/typicalRouteRouteList.xml
  src/test/data/XmlUtilTest/invalidDeliverymanField.xml
  src/test/data/XmlUtilTest/invalidOrderField.xml
  src/test/data/XmlUtilTest/missingOrderField.xml
  src/test/data/XmlUtilTest/validDeliveryman.xml
  src/test/data/XmlUtilTest/validDeliverymenList.xml
  src/test/data/XmlUtilTest/validOrder.xml
  src/test/data/XmlUtilTest/validOrderBook.xml
  src/test/java/seedu/address/commons/util/XmlUtilTest.java
  src/test/java/seedu/address/logic/commands/order/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/route/CreateRouteCommandTest.java
  src/test/java/seedu/address/storage/XmlAdaptedOrderTest.java
  src/test/java/seedu/address/storage/deliveryman/XmlAdaptedDeliverymanTest.java
  src/test/java/seedu/address/storage/deliveryman/XmlSerializableDeliverymenListTest.java
  src/test/java/seedu/address/storage/route/XmlAdaptedRouteTest.java
  src/test/java/seedu/address/testutil/DeliverymanBuilder.java
  src/test/java/seedu/address/testutil/OrderBuilder.java
  src/test/java/seedu/address/testutil/TypicalDeliverymen.java
  src/test/java/seedu/address/testutil/TypicalOrders.java
  src/test/java/seedu/address/testutil/TypicalRoutes.java
  src/test/java/seedu/address/testutil/route/RouteBuilder.java
  src/test/java/seedu/address/ui/OrderListPanelTest.java
  src/test/java/systemtests/AddCommandSystemTest.java
  src/test/java/systemtests/EditCommandSystemTest.java
  src/test/java/systemtests/OrderBookSystemTest.java
Labels: priority.High, v1.2

#80 Update UserGuide for V1.2
  docs/UserGuide.adoc
Labels: v1.2

#90 Update DG for v1.3
  docs/DeveloperGuide.adoc
  docs/diagrams/UndoRedoActivityDiagram.pptx
  docs/diagrams/UndoRedoExecuteUndoStateListDiagram.pptx
  docs/diagrams/UndoRedoNewCommand1StateListDiagram.pptx
  docs/diagrams/UndoRedoNewCommand2StateListDiagram.pptx
  docs/diagrams/UndoRedoNewCommand3StateListDiagram.pptx
  docs/diagrams/UndoRedoNewCommand4StateListDiagram.pptx
  docs/diagrams/UndoRedoSequenceDiagram.pptx
  docs/diagrams/UndoRedoStartingStateListDiagram.pptx
  docs/images/UndoRedoActivityDiagram.png
  docs/images/UndoRedoExecuteUndoStateListDiagram.png
  docs/images/UndoRedoNewCommand1StateListDiagram.png
  docs/images/UndoRedoNewCommand2StateListDiagram.png
  docs/images/UndoRedoNewCommand3StateListDiagram.png
  docs/images/UndoRedoNewCommand4StateListDiagram.png
  docs/images/UndoRedoSequenceDiagram.png
  docs/images/UndoRedoStartingStateListDiagram.png
Labels: priority.High, v1.3

#88 Add Status Field to Order
  src/main/java/seedu/address/model/order/Order.java
  src/main/java/seedu/address/model/order/OrderStatus.java
  src/main/java/seedu/address/storage/XmlAdaptedOrder.java
  src/test/data/XmlOrderBookStorageTest/invalidAndValidOrderOrderBook.xml
  src/test/data/XmlOrderBookStorageTest/invalidOrderOrderBook.xml
  src/test/data/XmlSerializableOrderBookTest/duplicateOrderOrderBook.xml
  src/test/data/XmlSerializableOrderBookTest/invalidOrderOrderBook.xml
  src/test/data/XmlSerializableOrderBookTest/typicalOrdersOrderBook.xml
  src/test/data/XmlUtilTest/invalidOrderField.xml
  src/test/data/XmlUtilTest/missingOrderField.xml
  src/test/data/XmlUtilTest/validOrder.xml
  src/test/data/XmlUtilTest/validOrderBook.xml
  src/test/java/seedu/address/commons/util/XmlUtilTest.java
  src/test/java/seedu/address/storage/XmlAdaptedOrderTest.java
  src/test/java/seedu/address/testutil/OrderBuilder.java
  src/test/java/seedu/address/testutil/TypicalOrders.java
  src/test/java/seedu/address/ui/OrderListPanelTest.java
Labels: priority.High, v1.3

#93 Improve Order Find Command
  src/main/java/seedu/address/logic/commands/order/FindCommand.java
  src/main/java/seedu/address/logic/parser/ArgumentMultimap.java
  src/main/java/seedu/address/logic/parser/order/FindCommandParser.java
  src/main/java/seedu/address/logic/parser/order/OrderDatePredicateUtil.java
  src/main/java/seedu/address/logic/parser/order/OrderPredicateUtil.java
  src/main/java/seedu/address/model/order/OrderAddressContainsKeywordPredicate.java
  src/main/java/seedu/address/model/order/OrderContainsAnyKeywordsPredicate.java
  src/main/java/seedu/address/model/order/OrderDate.java
  src/main/java/seedu/address/model/order/OrderDatePredicate.java
  src/main/java/seedu/address/model/order/OrderDateRangePredicate.java
  src/main/java/seedu/address/model/order/OrderDateSinglePredicate.java
  src/main/java/seedu/address/model/order/OrderFoodContainsKeywordPredicate.java
  src/main/java/seedu/address/model/order/OrderNameContainsKeywordPredicate.java
  src/main/java/seedu/address/model/order/OrderPhoneContainsKeywordPredicate.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/test/data/XmlSerializableOrderBookTest/typicalOrdersOrderBook.xml
  src/test/data/XmlSerializableRouteListTest/typicalRouteRouteList.xml
  src/test/java/seedu/address/logic/commands/order/FindCommandTest.java
  src/test/java/seedu/address/logic/parser/order/FindCommandParserTest.java
  src/test/java/seedu/address/logic/parser/order/OrderDatePredicateUtilTest.java
  src/test/java/seedu/address/logic/parser/order/OrderPredicateUtilTest.java
  src/test/java/seedu/address/model/order/OrderAddressContainsKeywordPredicateTest.java
  src/test/java/seedu/address/model/order/OrderDatePredicateTest.java
  src/test/java/seedu/address/model/order/OrderDateRangePredicateTest.java
  src/test/java/seedu/address/model/order/OrderDateSinglePredicateTest.java
  src/test/java/seedu/address/model/order/OrderFoodContainsKeywordPredicateTest.java
  src/test/java/seedu/address/model/order/OrderNameContainsKeywordPredicateTest.java
  src/test/java/seedu/address/model/order/OrderPhoneContainsKeywordPredicateTest.java
  src/test/java/seedu/address/testutil/TypicalOrders.java
  src/test/java/systemtests/FindCommandSystemTest.java
Labels: priority.Medium, severity.Medium, v1.3

#97 Documents update
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
Labels: v1.3

#92 Username Fixes
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/ui/StatusBarFooter.java
  src/main/resources/view/StatusBarFooter.fxml
Labels: bug, priority.Medium, v1.3

#105 Update /exit
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
Labels: bug, v1.3

#101 Fix UI sizing
  src/main/java/seedu/address/ui/Dashboard.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/MapPanel.java
  src/main/resources/view/Dashboard.fxml
  src/main/resources/view/MapPanel.fxml
Labels: v1.3

#96 Fixed NAME and USERNAME length
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/LoginCommand.java
  src/main/java/seedu/address/logic/commands/SignUpCommand.java
  src/main/java/seedu/address/logic/commands/order/AddCommand.java
  src/main/java/seedu/address/model/common/Name.java
  src/main/java/seedu/address/model/common/Username.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/LoginCommandTest.java
  src/test/java/seedu/address/logic/commands/SignUpCommandTest.java
  src/test/java/seedu/address/ui/CommandBoxTest.java
  src/test/java/systemtests/LoginCommandSystemTest.java
  src/test/java/systemtests/SignUpCommandSystemTest.java
Labels: priority.High, v1.3

#106 Update UG and DG on /route and /assign
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
Labels: v1.3

#94 Modify saving & loading to XML
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/commons/events/model/DeliverymenListChangedEvent.java
  src/main/java/seedu/address/commons/events/model/FoodZoomChangedEvent.java
  src/main/java/seedu/address/commons/events/model/OrderBookChangedEvent.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/storage/FoodZoomStorage.java
  src/main/java/seedu/address/storage/Storage.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/main/java/seedu/address/storage/XmlAdaptedOrder.java
  src/main/java/seedu/address/storage/XmlFileStorage.java
  src/main/java/seedu/address/storage/XmlFoodZoom.java
  src/main/java/seedu/address/storage/XmlFoodZoomStorage.java
  src/main/java/seedu/address/storage/XmlOrderBookStorage.java
  src/main/java/seedu/address/storage/XmlSerializableOrderBook.java
  src/main/java/seedu/address/storage/deliveryman/XmlAdaptedDeliveryman.java
  src/main/java/seedu/address/storage/deliveryman/XmlDeliverymenListStorage.java
  src/main/java/seedu/address/storage/deliveryman/XmlSerializableDeliverymenList.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/StatusBarFooter.java
  src/test/data/JsonUserPrefsStorageTest/ExtraValuesUserPref.json
  src/test/data/JsonUserPrefsStorageTest/TypicalUserPref.json
  src/test/data/XmlFoodZoomTest/invalidFoodZoom.xml
  src/test/data/XmlFoodZoomTest/typicalFoodZoom.xml
  src/test/java/seedu/address/TestApp.java
  src/test/java/seedu/address/commons/util/XmlUtilTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/storage/JsonUserPrefsStorageTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
  src/test/java/seedu/address/storage/XmlFoodZoomTest.java
  src/test/java/seedu/address/storage/XmlOrderBookStorageTest.java
  src/test/java/seedu/address/storage/XmlSerializableOrderBookTest.java
  src/test/java/seedu/address/storage/deliveryman/XmlDeliverymenListStorageTest.java
  src/test/java/seedu/address/storage/deliveryman/XmlSerializableDeliverymenListTest.java
  src/test/java/seedu/address/ui/OrderListPanelTest.java
  src/test/java/seedu/address/ui/StatusBarFooterTest.java
  src/test/java/systemtests/OrderBookSystemTest.java
  src/test/java/systemtests/SampleDataTest.java
  src/test/java/systemtests/SystemTestSetupHelper.java
Labels: priority.High, v1.3

#99 Add postal code and extra validation to Address
  src/main/java/seedu/address/logic/commands/order/AddCommand.java
  src/main/java/seedu/address/model/common/Address.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/test/data/XmlOrderBookStorageTest/invalidAndValidOrderOrderBook.xml
  src/test/data/XmlOrderBookStorageTest/invalidOrderOrderBook.xml
  src/test/data/XmlSerializableOrderBookTest/duplicateOrderOrderBook.xml
  src/test/data/XmlSerializableOrderBookTest/invalidOrderOrderBook.xml
  src/test/data/XmlSerializableOrderBookTest/typicalOrdersOrderBook.xml
  src/test/data/XmlUtilTest/invalidOrderField.xml
  src/test/data/XmlUtilTest/missingOrderField.xml
  src/test/data/XmlUtilTest/validOrder.xml
  src/test/data/XmlUtilTest/validOrderBook.xml
  src/test/java/seedu/address/commons/util/XmlUtilTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/common/AddressTest.java
  src/test/java/seedu/address/model/order/OrderAddressContainsKeywordPredicateTest.java
  src/test/java/seedu/address/testutil/OrderBuilder.java
  src/test/java/seedu/address/testutil/TypicalOrders.java
  src/test/java/seedu/address/ui/OrderListPanelTest.java
Labels: v1.3

#104 Order Selection Fix for UI
  src/main/java/seedu/address/commons/events/ui/JumpToDeliveryManListRequestEvent.java
  src/main/java/seedu/address/commons/events/ui/JumpToOrderListRequestEvent.java
  src/main/java/seedu/address/logic/commands/order/SelectCommand.java
  src/main/java/seedu/address/ui/DeliverymanListPanel.java
  src/main/java/seedu/address/ui/OrderListPanel.java
  src/main/resources/view/TestTheme.css
  src/test/java/seedu/address/logic/commands/order/SelectCommandTest.java
  src/test/java/seedu/address/ui/BrowserPanelTest.java
  src/test/java/seedu/address/ui/OrderListPanelTest.java
Labels: v1.3

#114 Fix XML files for XmlFoodZoomTest
  src/test/data/XmlFoodZoomTest/typicalFoodZoom.xml
Labels: type.Bug

#108 Update order status, prevent deliverymen deletion, order deletion and order clear if order is assigned
  docs/UserGuide.adoc
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/deliveryman/DeliverymanDeleteCommand.java
  src/main/java/seedu/address/logic/commands/order/ClearCommand.java
  src/main/java/seedu/address/logic/commands/order/DeleteCommand.java
  src/main/java/seedu/address/model/deliveryman/Deliveryman.java
  src/main/java/seedu/address/model/order/Order.java
  src/main/java/seedu/address/ui/OrderCard.java
  src/main/resources/view/TestTheme.css
Labels: v1.3

#117 Update UG for v1.3
  docs/UserGuide.adoc
Labels: v1.3

#110 WIP: Add side panel view for Deliveryman
  src/main/java/seedu/address/ui/DeliverymanCard.java
  src/main/java/seedu/address/ui/DeliverymanListPanel.java
  src/main/java/seedu/address/ui/Display.java
  src/main/java/seedu/address/ui/OrderCard.java
  src/main/java/seedu/address/ui/OrderListPanel.java
  src/main/java/seedu/address/ui/display/DeliverymanDisplayCard.java
  src/main/java/seedu/address/ui/display/OrderDisplayCard.java
  src/main/java/seedu/address/ui/display/OrderDisplayListCard.java
  src/main/resources/view/DeliverymanListCard.fxml
  src/main/resources/view/Display.fxml
  src/main/resources/view/Extensions.css
  src/main/resources/view/TestTheme.css
  src/main/resources/view/display/DeliverymanDisplayCard.fxml
  src/main/resources/view/display/OrderDIsplayListCard.fxml
  src/main/resources/view/display/OrderDisplayCard.fxml
  src/test/java/guitests/guihandles/OrderCardHandle.java
Labels: type.Enhancement, v1.3

#116 Update Documentation for v1.3
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/OrderDatePredicate.png
  docs/images/OrderFindSequenceDiagram.png
Labels: v1.3

#118 Update Ui.png
  docs/images/Ui.png
Labels: priority.High, v1.3
